name: konflux-ci/application-api
exclude_dirs:
    - vendor/
    - .github/
    - .tekton/
    - hack/
    - proto/
    - test/
    - tests/
    - integration-tests/
    - /fake(/|$)
    - /mock(s)?(/|$)
    - /e2e(-tests)?(/|$)
    - docs/
    - config/
    - manifests/
exclude_files:
    - zz_generated.deepcopy.go
    - openapi_generated.go
    - '*.pb.go'
    - mock_*.go
    - '*_mock.go'
